/* Brio IA node registry - single source of truth for the Structure hub chips.
   Each node: { num, name, file, type, group("global"|"pages") }.
   The long node list lives ONLY here and in structure.html; never in the sidebar. */
window.BRIO_NODES = [
  { num: "0.0", name: "Home", file: "home.html", type: "page", group: "pages" },
  { num: "0.1", name: "Navigation", file: "navigation.html", type: "section", group: "global" },
  { num: "0.2", name: "Footer", file: "footer.html", type: "section", group: "global" },
  { num: "0.3", name: "Privacy-disclosure component", file: "privacy-disclosure.html", type: "section", group: "global" },
  { num: "0.4", name: "Program card", file: "program-card.html", type: "section", group: "global" },
  { num: "0.5", name: "Dialog / modal shell", file: "dialog.html", type: "dialog", group: "global" },
  { num: "0.6", name: "Canonical lists", file: "canonical-lists.html", type: "section", group: "global" },
  { num: "1.0", name: "Pricing", file: "pricing.html", type: "page", group: "pages" },
  { num: "1.1", name: "Security and privacy", file: "security-privacy.html", type: "page", group: "pages" },
  { num: "1.2", name: "About", file: "about.html", type: "page", group: "pages" },
  { num: "1.3", name: "Contact / Support", file: "contact.html", type: "page", group: "pages" },
  { num: "1.4", name: "Help / FAQ", file: "help.html", type: "page", group: "pages" },
  { num: "1.5", name: "Category / segment landing", file: "segment-landing.html", type: "page", group: "pages" },
  { num: "1.6", name: "Legal documents", file: "legal.html", type: "page", group: "pages" },
  { num: "2.0", name: "Sign up", file: "signup.html", type: "page", group: "pages" },
  { num: "2.1", name: "Log in", file: "login.html", type: "page", group: "pages" },
  { num: "2.2", name: "Magic-link sent", file: "magic-link-sent.html", type: "state", group: "pages" },
  { num: "2.3", name: "Invalid or expired link", file: "link-expired.html", type: "state", group: "pages" },
  { num: "2.4", name: "Reset password", file: "reset-password.html", type: "page", group: "pages" },
  { num: "3.0", name: "Company setup", file: "onboarding-company.html", type: "page", group: "pages" },
  { num: "3.1", name: "First program confirm", file: "onboarding-program.html", type: "page", group: "pages" },
  { num: "3.2", name: "Invite team", file: "onboarding-invite.html", type: "page", group: "pages" },
  { num: "3.3", name: "Invite-send error", file: "invite-send-error.html", type: "state", group: "pages" },
  { num: "4.0", name: "Dashboard", file: "dashboard.html", type: "page", group: "pages" },
  { num: "4.1", name: "Team pulse detail", file: "team-pulse.html", type: "page", group: "pages" },
  { num: "4.2", name: "Threshold alert detail", file: "threshold-alert.html", type: "page", group: "pages" },
  { num: "5.0", name: "Program library", file: "program-library.html", type: "page", group: "pages" },
  { num: "5.1", name: "Program detail / manage", file: "program-detail.html", type: "page", group: "pages" },
  { num: "5.2", name: "Check-in setup", file: "check-in-setup.html", type: "page", group: "pages" },
  { num: "6.0", name: "Team roster", file: "team-roster.html", type: "page", group: "pages" },
  { num: "6.1", name: "Resend or manage invite", file: "manage-invite.html", type: "dialog", group: "pages" },
  { num: "7.0", name: "Share with owner", file: "share-owner.html", type: "page / section", group: "pages" },
  { num: "7.1", name: "Invite owner + upgrade", file: "invite-owner.html", type: "page", group: "pages" },
  { num: "7.2", name: "Upgrade / paywall", file: "upgrade.html", type: "dialog", group: "pages" },
  { num: "7.3", name: "Payment failed", file: "payment-failed.html", type: "state", group: "pages" },
  { num: "8.0", name: "Settings shell", file: "settings.html", type: "page", group: "pages" },
  { num: "8.1", name: "Plan / subscription", file: "settings-plan.html", type: "section", group: "pages" },
  { num: "8.2", name: "Privacy center", file: "settings-privacy.html", type: "section", group: "pages" },
  { num: "8.3", name: "Notifications", file: "settings-notifications.html", type: "section", group: "pages" },
  { num: "8.4", name: "Account settings", file: "settings-account.html", type: "section", group: "pages" },
  { num: "9.0", name: "Owner dashboard", file: "owner-dashboard.html", type: "page", group: "pages" },
  { num: "9.2", name: "Monthly owner digest", file: "owner-digest.html", type: "page", group: "pages" },
  { num: "10.0", name: "Check-in entry", file: "checkin-entry.html", type: "flow entry", group: "pages" },
  { num: "10.1", name: "Pre-Q1 privacy disclosure", file: "checkin-privacy.html", type: "section", group: "pages" },
  { num: "10.2", name: "Questions", file: "checkin-questions.html", type: "page", group: "pages" },
  { num: "10.3", name: "Check-in complete", file: "checkin-complete.html", type: "page", group: "pages" },
  { num: "10.4", name: "Invite link expired", file: "checkin-expired.html", type: "state", group: "pages" },
  { num: "10.5", name: "Already submitted", file: "checkin-already.html", type: "state", group: "pages" },
  { num: "10.6", name: "Submit error", file: "checkin-submit-error.html", type: "state", group: "pages" },
  { num: "11.0", name: "404 Not found", file: "not-found.html", type: "page", group: "pages" },
  { num: "11.1", name: "500 Server error", file: "server-error.html", type: "page", group: "pages" },
  { num: "11.2", name: "Maintenance", file: "maintenance.html", type: "page", group: "pages" },
  { num: "11.3", name: "Cookie consent", file: "cookie-consent.html", type: "dialog", group: "pages" },
  { num: "11.4", name: "Toast / inline notification", file: "toast.html", type: "section", group: "pages" },
];
